(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/image/demo"],{

/***/ "./node_modules/bisheng/tmp/components-image-demo.index.js":
/*!*****************************************************************!*\
  !*** ./node_modules/bisheng/tmp/components-image-demo.index.js ***!
  \*****************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports = {\n    'basic': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/basic.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/basic.md\"),\n    'controlled-preview': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/controlled-preview.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/controlled-preview.md\"),\n    'fallback': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/fallback.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/fallback.md\"),\n    'placeholder': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/placeholder.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/placeholder.md\"),\n    'preview-group-visible': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/preview-group-visible.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/preview-group-visible.md\"),\n    'preview-group': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/preview-group.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/preview-group.md\"),\n    'preview-mask': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/preview-mask.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/preview-mask.md\"),\n    'previewSrc': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/image/demo/previewSrc.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/image/demo/previewSrc.md\"),\n}\n\n//# sourceURL=webpack:///./node_modules/bisheng/tmp/components-image-demo.index.js?");

/***/ })

}]);