(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["components/descriptions/demo"],{

/***/ "./node_modules/bisheng/tmp/components-descriptions-demo.index.js":
/*!************************************************************************!*\
  !*** ./node_modules/bisheng/tmp/components-descriptions-demo.index.js ***!
  \************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

eval("module.exports = {\n    'basic': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/basic.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/basic.md\"),\n    'border': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/border.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/border.md\"),\n    'responsive': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/responsive.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/responsive.md\"),\n    'size': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/size.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/size.md\"),\n    'style': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/style.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/style.md\"),\n    'text': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/text.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/text.md\"),\n    'vertical-border': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/vertical-border.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/vertical-border.md\"),\n    'vertical': __webpack_require__(/*! ./node_modules/bisheng/lib/loaders/source-loader!./components/descriptions/demo/vertical.md */ \"/Users/ianwong/Documents/demo/ant-design-doc/node_modules/bisheng/lib/loaders/source-loader!/Users/ianwong/Documents/demo/ant-design-doc/components/descriptions/demo/vertical.md\"),\n}\n\n//# sourceURL=webpack:///./node_modules/bisheng/tmp/components-descriptions-demo.index.js?");

/***/ })

}]);